name: flight_book
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.2.0
  table_calendar: ^3.0.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
